RunMode = "dev"
AppName = "dev-tool-service"
AutoRender = false
CopyRequestBody = true
EnableDocs = true
SQLConn = ""
DEFAULT_LANG = "vi"
ERROR_MESSAGE_FILE_PATH = "./conf/errors.yml"
TNG_CLIENT_KEY = "ce00580d6b3d1e0d7b7b8ec5eab0bc89"
HTTPPort = 8087

DB_DRIVER = "mysql"
DB_USERNAME = "root"
DB_PASSWORD = "root"
DB_HOST = "127.0.0.1"
DB_PORT = "3306"
DB_DATABASE = "dev_tool"
DB_MAX_IDLE = "5"
DB_MAX_CONNECTION = "10"

ALLOW_DOMAIN_FE = ""

MQTT_HOST = "tcp://127.0.0.1:1883"
MQTT_PATH = ""